### DISCUSSION TITLE
Validation error when using expression for env

### DISCUSSION THREAD

**Discussion by h-haaks** [github/vscode-github-actions#344] [Q&A]
I have something like this in my jobs definition
```
...
jobs:
  test:
    steps:
      - name: run command
        run: command
        env: ${{ matrix.env }}
```
In VSCode I get the following error
`Unexpected type 'BasicExpressionToken' encountered while reading 'step env'. The type 'MappingToken' was expected.`

The workflow runs just fine so i wonder if this is a bug in the vscode extension?
