### DISCUSSION TITLE
I want to catch syntax error in shell script

### DISCUSSION THREAD

**Discussion by AobaIwaki123** [github/vscode-github-actions#412] [Q&A]
These days, I'm working with GitHub Actions.
Then, I found scripts which have syntax error do not return error code and so workflow does not notice the error.
For example, the code below has syntax error.
But it returns 0 as exit code so workflow does not notice the step is failed.
Is there any way to catch this error?

- Error
```diff
- while [ "$flag" = "false"]; do
+ while [ "$flag" = "false" ]; do
```
- Example Workflow
```yaml
name: Syntax Error Script
on:
  push:
jobs:
  syntax-error-script:
    runs-on: ubuntu-latest
    steps:
      - name: Syntax Error Script
        shell: bash
        run: |
          set -e
          flag=false
          while [ "$flag" = "false"]; do
              flag=true
          done

 ```
