### ISSUE TITLE
Extra indentation added for mapping keys

### ISSUE THREAD

**Issue by jtamsut** [github/vscode-github-actions#124]
**Describe the bug**

Autocomplete for mapping keys adds an extra newline and indentation when already in a mapping key.

**To Reproduce**

Using the YAML file below go to the line below `group: stuff` and hit Ctrl+space (or whatever the equivalent autocomplete command is for you):

```yaml
name: Simple Workflow
concurrency:
  group: stuff

on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: this is a step
          run: echo step1
```
**Expected behavior**
No error.

**Screenshots**

https://github.com/github/vscode-github-actions/assets/7937889/63373cba-2aec-4d4c-8038-02d49fcb5204

**Extension Version**
`v0.25.5`
