### ISSUE TITLE
Support local actions defined in repository

### ISSUE THREAD

**Issue by paul-sachs** [github/vscode-github-actions#134]
**Is your feature request related to a problem? Please describe.**
I have a few locally created actions in the `.github/actions` directory but validation and autocomplete don't seem to work on these actions.

I have the following yaml file at `.github/actions/wait-for-deployment-action`

```yaml
name: Wait for deployment
description: |
  Block until a deployment is finished for the pushed commit,
  and get the URL for running any further tests.
branding:
  icon: clock
  color: black

inputs:
  github-token:
    description: Your GitHub access token
    required: true
  environment:
    description: The deployment environment to wait for
  timeout:
    description: The number of seconds after which to fail if no deployment is found.
    default: 30
  interval:
    description: The number of seconds to wait between repeated checks for deployments.
    default: 5
  sha:
    description: |
      The commit SHA to wait for. Defaults to the current commit SHA. For PRs, this is the merge commit SHA.
      So provide ${{ github.event.pull_request.head.sha }} instead.

outputs:
  url:
    description: The deployment URL
  id:
    description: The GitHub deployment id

runs:
  using: node16
  main: dist/index.js
```

The below shows an attempt to autocomplete the params expected by a local action:
<img width="480" alt="image" src="https://github.com/github/vscode-github-actions/assets/11449728/0c5e4f22-d1bd-47a2-9e6f-c3d3e4d655db">

**Describe the solution you'd like**
For local actions to be validated and provide autocomplete for locally defined actions.
