### ISSUE TITLE
Workflows with identical concurrency groups at workflow and job level appear valid but will never run

### ISSUE THREAD

**Issue by thyeggman** [github/vscode-github-actions#135]
**Describe the bug**
If a concurrency group is defined at the workflow level, and the same concurrency group is defined at the job level, the job will never run.  It will be skipped with the following error: 

```
Canceling since a deadlock for concurrency group '<group name>' was detected between 'top level workflow' and '<job name>'
```

These workflows do not produce any warnings in the editor, even though they will never run. [Here](https://github.com/bbq-beets/thyeggman-lab-public/actions/runs/4759588246) is a link to a workflow run that is skipped in this way.

**To Reproduce**
1. Create this workflow:

```yaml
on:
  workflow_dispatch:
concurrency: test

jobs:
  deadlock:
    runs-on: ubuntu-latest
    concurrency: test
    steps:
      - name: echo something
        run: echo "Hi"
```

2. Observe that there are no warnings or errors in the editor

**Expected behavior**
One or both concurrency groups should have a warning (yellow underline) with a note mentioning that there will be a conflict between identical concurrency groups in the same workflow.

**Screenshots**
Workflow showing no errors:

<img width="333" alt="image" src="https://github.com/github/vscode-github-actions/assets/13154238/e2fde2ec-60c1-4a77-8bbb-8895913ea41b">

**Extension Version**
`v0.25.5`
