### ISSUE TITLE
`if` expression syntax highlighting doesn't seem to respect comments

### ISSUE THREAD

**Issue by max-sixty** [github/vscode-github-actions#158]
**Describe the bug**

Here, this line should appear as a comment:

<img width="525" alt="image" src="https://github.com/github/vscode-github-actions/assets/5635139/2e447487-dff6-4c8c-8315-02a576a3e57a">

**To Reproduce**

Here's the text:

```yaml
  update-rust-toolchain:
    runs-on: ubuntu-latest
    # Don't run on forks; will attempt to create a PR into the fork...

    # if: ${{ !github.event.pull_request.head.repo.fork }}
```

**Extension Version**
`v0.25.6`
