### ISSUE TITLE
Supporting `actions/github-script` step named outputs

### ISSUE THREAD

**Issue by Drarig29** [github/vscode-github-actions#188]
**Is your feature request related to a problem? Please describe.**

When using https://github.com/actions/github-script with a call to `core.setOutput()`, the VSCode extension is unable to do autocompletion and shows "Context access might be invalid" warnings.

The usual way of setting outputs with `actions/github-script` is to use a `return` statement, which creates a `result` output, accessible with `steps.<step-id>.outputs.result` (https://github.com/actions/github-script#reading-step-results).

But we preferred to use the reference to the `core` API to set **named outputs** instead.

**Example:**
```yaml
- uses: actions/github-script@v6
  id: get-versions
  with:
    script: |
      const currentVersion = 'v1.0.0'
      const nextVersion = 'v1.1.0'

      core.setOutput('CURRENT_VERSION', currentVersion)
      core.setOutput('NEXT_VERSION', nextVersion)
- name: Use versions
  run: |
    echo "Current version: ${{ steps.get-version.outputs.CURRENT_VERSION }}"
    echo "Next version: ${{ steps.get-version.outputs.NEXT_VERSION }}"
```

**Describe the solution you'd like**

The VSCode extension should be able to read the inline scripts passed to your official `actions/github-script` action, and detect all the calls to `core.setOutput()` to provide autocompletion.

And realistically, I can understand that https://github.com/actions/github-script#run-a-separate-file would be a limitation. Trying to find all `require` statements, reading those files recursively, etc. would be too much for this VSCode extension. Or you would have to include some kind of bundling to find all the `core.setOutput()` in the import tree.
