### ISSUE TITLE
Checkbox for Boolean inputs when triggering `workflow_dispatch`

### ISSUE THREAD

**Issue by AdamRaichu** [github/vscode-github-actions#190]
**Is your feature request related to a problem? Please describe.**
When triggering a workflow via the view in vscode, the extension asks for input values. Currently, it generates an error when giving a string that is not `true` or `false` for boolean inputs.

**Describe the solution you'd like**
Use a checkbox input instead of a string input when asking vscode user for input.

**Additional context**

**Comment by felipesu19** [comment]
I'm unclear on what the issue is here, any chance you could take a screenshot?

**Comment by AdamRaichu** [comment]
![image](https://github.com/github/vscode-github-actions/assets/91494019/3716169a-73f3-462e-9ee0-854af667fb93)

I activated "Publish Extension" using the button in the view on the left. It asked for a ref (for which I used the default), then asked for the `preRelease` input, which as you can see from the screenshot (and code below) is of type `boolean`. However, it accepts a string answer. Giving a value such as `falseeee` gives an error message, but it would be better if it accepted the input as a checkbox instead of a text input.

```yml
# Workflow File
name: Publish Extension
on:
  workflow_dispatch:
    inputs:
      preRelease:
        type: boolean
        required: true
        default: false
      continueOnTagErr:
        type: boolean
        required: false
        default: false
  # ...
```

```txt
# Error when using invalid input value.
Could not create workflow dispatch: Provided value 'falseeeeeeeee' for input 'preRelease' not in the list of allowed values
```
