### ISSUE TITLE
Showing error when using  >>  "$GITHUB_ENV"

### ISSUE THREAD

**Issue by Martin-Carlsson** [github/vscode-github-actions#199]
**Describe the bug**
After updating code to adhere to [GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) [vscode-github-actions](https://github.com/github/vscode-github-actions) started to show errors in code.

**To Reproduce**
```
      - name: Read Python version from .python-version
        run: echo "python_version=$(cat .python-version)" >>  "$GITHUB_ENV"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
```

**Expected behavior**
No errors.

**Screenshots**

The error:
<img width="833" alt="image" src="https://github.com/github/vscode-github-actions/assets/7769335/f1eb4bd0-81d1-4100-bcb7-6e52bfdbfd81">

The GitHub Action log showing the code runs without problems:
<img width="1089" alt="image" src="https://github.com/github/vscode-github-actions/assets/7769335/0863f317-c056-4ed8-be6f-38b728eba039">

**Extension Version**
`v0.25.7`

**Additional context**
VSCode version: `1.79.0-insider`

I am using Visual Studio Code Dev Containers

The action is running fine as a GitHub Action.

**The entire code, for context**
```
name: YAMLLint

on:
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Read Python version from .python-version
        run: echo "python_version=$(cat .python-version)" >>  "$GITHUB_ENV"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          grep yamllint requirements.txt | xargs -n 1 pip install

      - name: Lint YAML files
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git ls-files --exclude-standard --cached --others -- '*.yaml' '*.yml' | xargs yamllint
```
