### ISSUE TITLE
"Nested mappings are not allowed in compact mappings"

### ISSUE THREAD

**Issue by reinierkaper-carewell** [github/vscode-github-actions#205]
**Describe the bug**
When adding a negation to a conditional `if`, the plugin throws the error `Nested mappings are not allowed in compact mappings`

**To Reproduce**
1. Using the below yml file
2. The plugin throws an error

```yml
name: Merge Check
run-name: ${{ github.actor }} is running merge checks 🚀
on: [pull_request]
jobs:
  fail-for-merge:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'status: 📦 Ready to merge') }} #error thrown on "${{"
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is ready to merge
        run: |
          echo "🚫 This PR is not yet ready to merge"
          exit 1
```

**Expected behavior**
The error not to be thrown, as this is the recommended way to do a negation of `contains` (https://github.com/orgs/community/discussions/26386)

**Screenshots**
<img width="734" alt="image" src="https://github.com/github/vscode-github-actions/assets/131210150/4563c9fe-f4d0-4292-b793-d8dd3d700313">

**Extension Version**
`v0.25.7`

**Comment by briceburg** [comment]
I too experience this. We use a label of `:rocket: deploy` on PRs to indicate the PR is deployable. A sample workflow:

```yml
name: PR Labels

on:
  pull_request:
    types: [labeled]

jobs:
  pr-deploy:
    if: contains(github.event.pull_request.labels.*.name, ':rocket: deploy')
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy...."
```

results in a invalid workflow file error. If I change the contains item lookup from `:rocket: deploy` to `deploy`, e.g. 

```
 if: contains(github.event.pull_request.labels.*.name, 'deploy')
```

things are groovy. this feels like a bug in `contains()`? where the item cannot include colons?
