### ISSUE TITLE
Environment 'github-pages' is not valid

### ISSUE THREAD

**Issue by kaikaibenkai** [github/vscode-github-actions#215]
**Describe the bug**

**To Reproduce**
```yml
jobs:
  xxx:
    name: xxx
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages # This Line
      url: ${{ steps.deployment.outputs.page_url }}
```
Error:
```log
Value 'github-pages' is not valid
```

**Expected behavior**
The environment already exists, so that error shouldn't be reported.
![image](https://github.com/github/vscode-github-actions/assets/99722991/07f5b715-b0fd-4f26-b9f4-629f96ad8636)

**Screenshots**
![image](https://github.com/github/vscode-github-actions/assets/99722991/31a2766f-f40c-4e0e-ad58-a48e585b9825)

**Extension Version**
`v0.25.7`
