### ISSUE TITLE
GitHub actions Workflow syntax highlight issues

### ISSUE THREAD

**Issue by caquino** [github/vscode-github-actions#223]
Type: <b>Bug</b>

Hi,

Given the following code:

```yaml
name: Example

on:
  push:

jobs:
  example:
    name: Example
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix: ${{ fromJSON( startsWith(inputs.linting, '{') && inputs.linting || format('{{"linting":["{0}"]}}', inputs.linting) ) }}

    steps:
      - run: echo "Example"
```

The matrix expression using fromJSON breaks syntax highlight

Extension version: 0.25.8
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:33.551Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|32.00GB (0.34GB free)|
|Process Argv|--crash-reporter-id 84717786-ecd9-4b5e-a3c9-9b80403c43aa|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30773603
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30770000
pythonidxpt:30772539
pythondjangotscf:30772537

```

</details>
