### ISSUE TITLE
Suggest to update a new major version of Action

### ISSUE THREAD

**Issue by bartekpacia** [github/vscode-github-actions#238]
**Describe the solution you'd like**

Let's say I use the `actions/setup-go` in my workflow file:

```yaml
- name: Set up Go
  uses: actions/setup-go@v3
  with:
    cache: true
    go-version-file: go.mod
```

I'd like this extension to show me yellow underline telling me to update to v4 of this action, so I'd have:

```yaml
- name: Set up Go
  uses: actions/setup-go@v4
  with:
    go-version-file: go.mod
```

Small feature but would be nice to have it!
