### ISSUE TITLE
`if` statement in comment not shown as comment (syntax highlighting)

### ISSUE THREAD

**Issue by AdamRaichu** [github/vscode-github-actions#259]
**Describe the bug**

**To Reproduce**
1. Create a new workflow file and paste in the below code.
2. Observe how `if: ...` is highlighted incorrectly.

```yml
name: Example Workflow File
on: 
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: A fake step
        run: echo Hello World
# This is a block comment
# The if: with a colon after it is not highlighted properly
# An if without a colon is fine.

```

**Expected behavior**
The `if:` and following text should remain grey like a comment.

**Screenshots**

![image](https://github.com/github/vscode-github-actions/assets/91494019/d6aca271-4675-445b-a98a-69bc62bf7079)

**Extension Version**
`v0.26.2`

**Additional context**

This seems slightly related to #158
