### ISSUE TITLE
Missing values error for provided values

### ISSUE THREAD

**Issue by Vino4** [github/vscode-github-actions#264]
**Describe the bug**
Some required values are highlighted with "Missing" error despite being provided

**To Reproduce**
1. With the `easingthemes/ssh-deploy` workflow version 4.1.8 (latest)
2. Fill in the required values:
```
      - name: Push Over SSH
        if: steps.checkTag.outputs.exists == 'false'
        uses: easingthemes/ssh-deploy@main
        env:
            SOURCE: "/api"
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            SCRIPT_BEFORE: |
              echo "[Running Pre-Rsync Script]"
              ...
            SCRIPT_AFTER: |
              echo "[Running Post-Rsync Script]"
              ...
```
3. See error:
> Missing required inputs: `SSH_PRIVATE_KEY`, `REMOTE_HOST`, `REMOTE_USER`

**Expected behavior**
No error should appear

**Screenshots**
<img width="705" alt="image" src="https://github.com/github/vscode-github-actions/assets/14026415/86df1bfa-220a-4d1e-b291-89d71c18bfd5">

**Extension Version**
`v0.26.2`

**Comment by muzimuzhi** [comment]
With `uses: easingthemes/ssh-deploy@main` the extension reads the corresponding [`action.yml`](https://github.com/easingthemes/ssh-deploy/blob/main/action.yml) and finds if all the required inputs are provided with [`jobs.<job_id>.steps[*].with`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith).

Since the corresponding `action.yml` marks those input all required,
```yaml
inputs:
  SSH_PRIVATE_KEY:
    description: "Private key part of an SSH key pair"
    required: true
  REMOTE_HOST:
    description: "Remote host"
    required: true
  REMOTE_USER:
    description: "Remote user"
    required: true
   # more inputs
```
error
> Missing required inputs: `SSH_PRIVATE_KEY`, `REMOTE_HOST`, `REMOTE_USER`

was thrown.

But action `easingthemes/ssh-deploy` is special. Use one of the three inputs `SSH_PRIVATE_KEY` as an example:
```yaml
- uses: easingthemes/ssh-deploy@main
  with:
    SSH_PRIVATE_KEY: some_value
```
According to the documentation for [`jobs.<job_id>.steps[*].with`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith), GitHub Action will convert this input to an environment variable  `INPUT_SSH_PRIVATE_KEY`, then the action to-be-used is expected to read the value of input `SSH_PRIVATE_KEY` through that environment variable. But `easingthemes/ssh-deploy` can also read from environment variable `SSH_PRIVATE_KEY`, without the prefix `INPUT_`, see its [related code](https://github.com/easingthemes/ssh-deploy/blob/cf583aab4f795049a9b06ceab8404ea398a22f3f/src/inputs.js#L27).

To some extent, I doubt if those three inputs are still required (for `jobs.<job_id>.steps[*].with`). But if GitHub Action tolerates this ...
