### ISSUE TITLE
Linter lints old version when comparing diffs

### ISSUE THREAD

**Issue by kristof-mattei** [github/vscode-github-actions#281]
**Describe the bug**

**To Reproduce**
1. Create & **commit** the following workflow:
    ```yaml
    # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
    name: Build
    
    on:
      pull_request:
        branches:
          - main
    
    permissions:
      contents: read
    
    jobs:
      build:
        name: Build
        runs-on: ubuntu-latest
        outputs:
          build_id: ${{ steps.build.build_id }}
        steps:
          - name: Checkout
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            with:
              show-progress: false
    
          - name: Build
            id: build
            shell: bash
            run: |
              echo "Building"
              echo "build_id=12345" >> "$GITHUB_OUTPUT"

    ```
1. Notice the linting warning on `${{ steps.build.build_id }}`: `Context access might be invalid: build_id`. 
1. Delete the following lines, save but do NOT commit:
    ```yaml
        outputs:
          build_id: ${{ steps.build.build_id }}
    ```
1. In the diff window compare the changes
1. (BUG 1) (while diff is open) Notice the LEFT window showing the linting warning, which also shows up under 'PROBLEMS'

    ![image](https://github.com/github/vscode-github-actions/assets/864376/0999a465-f442-47f3-b4e7-18d45d115e8a)

1. (while diff is open) Double click the warning under problems and notice it opens a locked (denoted the padlock next to the name) version of the previous, unedited version of `build.yaml`.

    ![image](https://github.com/github/vscode-github-actions/assets/864376/22c71f57-4952-4b89-a2f1-02aa328d24c7)

1. Close the diff & locked old version of `build.yaml`
1. (BUG 2) Notice the linting error is still there under 'PROBLEMS'
    
    ![image](https://github.com/github/vscode-github-actions/assets/864376/6e70e611-897e-413a-93f1-a224f2fd8f3e)

1. (BUG 2 related) When double clicking linting warning it opens up the same locked (denoted the padlock next to the name) version of the previous, unedited version of `build.yaml`.
1. (BUG 1) Now when hitting 'CTRL+P' to switch between files there are 2 entries for `build.yaml` which are indistinguishable, yet refer to different versions:
    
    ![image](https://github.com/github/vscode-github-actions/assets/864376/387abf74-0a8a-46ab-b8a1-8bac46b6e41b)

**Expected behavior**
Only errors on the new version are reported.

**Screenshots**
See reproduction

**Extension Version**
`v0.26.2`

**Additional context**
