### ISSUE TITLE
"Context access might be invalid: <outputs>" showed up for 'dorny/paths-filter' GitHub Action

### ISSUE THREAD

**Issue by hwhsu1231** [github/vscode-github-actions#305]
**Describe the bug**

I found that the outputs of [`dorny/paths-filter@v3`](https://github.com/dorny/paths-filter/tree/v3/) cannot be accessed with the following warning messages:

```
Context access might be invalid: cmake
```

However, the outputs of [`tibdex/github-app-token@v2`](https://github.com/tibdex/github-app-token/tree/v2/) can be accessed without the above warning messages.

See the screenshots of these two in **Screenshots**.

For the records, although the warning messages showed up, the outputs of `dorny/paths-filter@v3` were printed correctly.

**To Reproduce**

Copy and paste the following two code snippets:

<details><summary>Click to expand demo of 'paths-filter'</summary>

```yml
      - name: Filter Changes in the Pull Request
        id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: 'json'
          filters: |
            cmake:
              - 'cmake/**/*.cmake'
              - 'CMakeLists.txt'
              - 'CMakePresets.json'
            document:
              - 'docs/ACKNOWLEDGEMENTS.md'
              - 'docs/CONTRIBUTING.md'
              - 'docs/MAINTAINING.md'
              - 'CODE_OF_CONDUCT.md'
              - 'README.md'
            workflow:
              - '.github/workflows/*.yml'
              - '.github/workflows/*.yaml'

      - name: Check Outputs of paths-filter
        run: |
          echo "steps.filter.outputs.cmake    = ${{ steps.filter.outputs.cmake }}"
          echo "steps.filter.outputs.document = ${{ steps.filter.outputs.document }}"
          echo "steps.filter.outputs.workflow = ${{ steps.filter.outputs.workflow }}"
          echo "steps.filter.outputs.cmake_count    = ${{ steps.filter.outputs.cmake_count }}"
          echo "steps.filter.outputs.document_count = ${{ steps.filter.outputs.document_count }}"
          echo "steps.filter.outputs.workflow_count = ${{ steps.filter.outputs.workflow_count }}"
          echo "steps.filter.outputs.cmake_files    = ${{ steps.filter.outputs.cmake_files }}"
          echo "steps.filter.outputs.document_files = ${{ steps.filter.outputs.document_files }}"
          echo "steps.filter.outputs.workflow_files = ${{ steps.filter.outputs.workflow_files }}"
```

</details>

<details><summary>Click to expand demo of 'github-app-token'</summary>

```yml
      - name: Get the GitHub App's Token
        uses: tibdex/github-app-token@v2
        id: ggat
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ steps.ggat.outputs.token }}
          submodules: true
```

</details>

**Expected behavior**

The warning messages shouldn't show up.

**Screenshots**

![Screenshot_20240311_110340](https://github.com/github/vscode-github-actions/assets/71438617/982e914d-f72d-4490-9491-9c77e7a974a9)
![image](https://github.com/github/vscode-github-actions/assets/71438617/3ba4f013-1836-4cbd-a794-b9bf300f2534)

**Extension Version**

`v0.26.2`

**Additional context**
