### ISSUE TITLE
`inputs` context shown as not allowed in `jobs.job.steps[].continue-on-error`

### ISSUE THREAD

**Issue by AdamRaichu** [github/vscode-github-actions#33]
**Describe the bug**
The extension shows an error when using the inputs context when expecting a Boolean, even though the input type is `boolean`.

**To Reproduce**
1. Create a workflow that has a `boolean` type input and a step with the `continue-on-error` option.
2. Reference the input using expression syntax. (See code example below).
3. Extension gives syntax error. `Unexpected type 'BasicExpressionToken' encountered while reading 'steps item continue-on-error'. The type 'BooleanToken' was expected.`

**Expected behavior**

Referencing a Boolean input should not generate this error.

**Screenshots**

![image](https://user-images.githubusercontent.com/91494019/227732863-f75d5385-9218-4241-ac6f-2e2c9d50b270.png)

**Extension Version**
`v0.25.2`

**Additional context**
Code generating the error.

```yaml
name: Publish Extension
on:
  workflow_dispatch:
    inputs:
      preRelease:
        type: boolean
        required: true
        default: false
      continueOnTagErr:
        type: boolean
        required: false
        default: false
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - uses: nyaa8/package-version@v1
      - name: Create a tag
        continue-on-error: ${{ inputs.continueOnTagErr }}
        run: |
          git config user.name = "Github Actions"
          git config user.email = "actions@github.com"
          git tag -a v${{ env.PACKAGE_VERSION }} -m "Version ${{ env.PACKAGE_VERSION }}"
          git push origin v${{ env.PACKAGE_VERSION }}
      - name: Generate Files
        run: |
          npm i
          npm run build
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.AZURE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          preRelease: ${{ inputs.preRelease }}
```
