### ISSUE TITLE
Value 'github-pages' is not valid

### ISSUE THREAD

**Issue by bennycode** [github/vscode-github-actions#369]
**Describe the bug**

The GitHub Actions extension for VS Code shows me that "github-pages" is not a supported environment.

**To Reproduce**

1. With this workflow: https://github.com/actions/deploy-pages?tab=readme-ov-file#usage
2. Do this: Open your ".github/workflows/deploy.yml" file
3. See error (the extensions shows: `Value 'github-pages' is not valid`)

**Expected behavior**

Accept "github-pages" as value.

**Screenshots**

![image](https://github.com/user-attachments/assets/ab1a8145-5185-4ee4-9db7-b71e204e2c79)

**Extension Version**
`v0.26.3`

**Additional context**

Here is my full workflow:

```yml
name: "Deploy Website"

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: "Build Website"
        run: npm ci && npm run build
      - name: "Upload artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    name: "Deploy"
    steps:
      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
```
