### ISSUE TITLE
false positive error on `secrets` context access in forks

### ISSUE THREAD

**Issue by OmarTawfik** [github/vscode-github-actions#375]
For a workflow that accesses secrets:

```yml
      - name: "publish npm"
        uses: "./.github/actions/publish-npm"
        env:
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
```

The extension is very helpful in checking if the secret `NPM_TOKEN` is actually defined or not.
However, it only checks secrets defined in the same repository (I suspect `origin` remote), and reports a false-positive error if it was defined in `upstream`, and `origin` is actually pointing to a fork:

> Context access might be invalid: NPM_TOKEN

**Expected behavior**

All remotes to be checked for secrets, not just `origin`, and the error is no longer reported.

**Screenshots**

<img width="650" alt="image" src="https://github.com/user-attachments/assets/7cc6576a-1a27-4338-9c3d-38c1ae7570a4">

**Extension Version**
`v0.26.3`
