### ISSUE TITLE
Incorrect report of `unexpected value: 'uses'` for reusable workflow called in matrix

### ISSUE THREAD

**Issue by dragonfleas** [github/vscode-github-actions#383]
**Describe the bug**
According to [GitHub's documentation](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow) calling a reusable workflow on the same key level as strategy is fine, and you can invoke them from the matrices and pass values in. The extension currently reports the fields of both `uses:` and `with:` as being invalid values when doing such. Screenshot below.

**To Reproduce**
1. Put the following into a workflow file
```
name: test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [1, 2]
    uses: ./reusable-workflow.yml
    with:
      input: test
```
2. See error

**Expected behavior**
You get proper Intellisense for the values, and also the formatter does not throw an error.

**Screenshots**

![image](https://github.com/user-attachments/assets/f2c44f90-a74e-48ff-b17a-da362e0c63a6)

**Extension Version**
`v0.26.3`

**Additional context**
N/A
