### ISSUE TITLE
Empty value for choice option shows "Unexpected value" error

### ISSUE THREAD

**Issue by ThiefMaster** [github/vscode-github-actions#395]
```yaml
on:
  # ...
  workflow_dispatch:
    inputs:
      plugin-name:
        description: Specific plugin to build
        type: choice
        options:
          - ''
          - foo
          - bar
```

This shows `Unexpected value ''` on the '``' line. But it's perfectly valid and unfortunately the only way to really make an optional choice field where one can decide to not select anything (and not get anything preselected). Likewise, it's the only way to make a required choice field where one is forced to actually make a choice and not just have the first option preselected.
