### ISSUE TITLE
YAML Alias Nodes break linting

### ISSUE THREAD

**Issue by harrydowning** [github/vscode-github-actions#404]
**Describe the bug**
Using YAML [Alias Nodes](https://yaml.org/spec/1.2.2/#alias-nodes) breaks linting:
- `Expected mapping end`
- `Unexpected value 'steps'`

**To Reproduce**
1. With this workflow

```yaml
name: pipeline

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env: &env
      ENV1: env1
      ENV2: env2
    steps:
      - run: exit 0
  job2:
    runs-on: ubuntu-latest
    env: *env
    steps:
      - run: exit 0
```

**Expected behavior**
No linting errors. 

**Screenshots**
![image](https://github.com/user-attachments/assets/6363988c-6baf-4bf8-9498-c73a39fb6de2)

**Extension Version**
`v0.27.0`

**Additional context**
N/A
