### ISSUE TITLE
Support YAML anchors and aliases

### ISSUE THREAD

**Issue by harrydowning** [github/vscode-github-actions#405]
**Is your feature request related to a problem? Please describe.**
Once github actions supports anchors and aliases (see https://github.com/actions/runner/issues/1182) this extension will need to be updated accordingly. Currently, using anchors and aliases results in errors:

![image](https://github.com/user-attachments/assets/34391a9f-8754-44bf-99a9-bb672470388e)

**Describe the solution you'd like**
Using anchors and aliases should not result in these linting errors.

**Additional context**
```yaml
name: pipeline

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env: &env
      ENV1: env1
      ENV2: env2
    steps:
      - run: exit 0
  job2:
    runs-on: ubuntu-latest
    env: *env
    steps:
      - run: exit 0
```
