### ISSUE TITLE
"Unable to resolve action" for any action

### ISSUE THREAD

**Issue by kalleguld** [github/vscode-github-actions#433]
Every action in an .yml file gives an error `Unable to resolve action `actions/checkout@v4`, repository or version not found` - even fundamental stuff like `- uses: actions/checkout@v4`

**To Reproduce**
- Make a file like this one (autogenerated by github.com):
```
name: .NET
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

```
- Open the Problems tab in VSCode.
- Lines 9 and 11 now give an error: 
```
[{
	"resource": "/[repo_path]/.github/workflows/dotnet.yml",
	"owner": "_generated_diagnostic_collection_name_#7",
	"severity": 8,
	"message": "Unable to resolve action `actions/checkout@v4`, repository or version not found",
	"startLineNumber": 9,
	"startColumn": 13,
	"endLineNumber": 9,
	"endColumn": 32
}]
```

**Expected behavior**
Expected no false errors.

**Screenshots**
<img width="897" alt="Screenshot 2024-12-15 at 17 51 22" src="https://github.com/user-attachments/assets/ba04d871-6de5-460b-a8f1-6cb21a242893" />

**Extension Version**
`v0.27.0`

**Additional context**
