### ISSUE TITLE
`Unrecognized named-value: 'matrix'` / `Available expression contexts: github, inputs, vars, needs, strategy, matrix, secrets, steps, job, runner, env`

### ISSUE THREAD

**Issue by jsoref** [github/vscode-github-actions#447]
Type: <b>Bug</b>

Create a `.github/workflows/ci.yml` file with:
```yaml
name: CI
on:
  push:
  workflow_dispatch: 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-arch:
    name: Build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            name: amd
          - os: ubuntu-24.04-arm
            name: arm

    runs-on: ${{ matrix.os }}
    outputs:
      attestation-url: ${{ steps.attestation.outputs.attestation-url }}
      ${{ matrix.name }}-attestation-url: ${{ steps.attestation.outputs.attestation-url }}
      my-matrix: ${{ matrix }}
      ${{ toJSON(matrix) }}: 'x'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        id: attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

          
  combine-images:
    name: Combine images
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

See a red-squiggly near `${{ matrix.name }}-attestation-url: ${{ steps.attestation.outputs.attestation-url }}`

Hover over `${{ matrix.name }}`

See:
```yaml
Unrecognized named-value: 'matrix'
Available expression contexts: github, inputs, vars, needs, strategy, matrix, secrets, steps, job, runner, env
```

View problem shows:
```yaml
Unrecognized named-value: 'matrix'
```

---

* If an expression is available, then it should be usable.
* If it isn't available, then it shouldn't be listed as available.

Extension version: 0.27.1
VS Code version: Code 1.98.0 (Universal) (6609ac3d66f4eade5cf376d1cb76f13985724bcb, 2025-03-04T21:06:18.612Z)
OS version: Darwin arm64 24.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|7, 9, 10|
|Memory (System)|64.00GB (0.87GB free)|
|Process Argv|--crash-reporter-id 1fc67ee2-0174-4598-9f98-4537df0dd32c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
iacca1:31171482
5fd0e150:31155592
dwcopilot:31170013
6074i472:31201624
dwoutputs:31242946
customenabled:31248079
5a9hg449:31230677
hdaa2157:31222309
copilot_t_ci:31222730
jda6j935:31233686

```

</details>

**Comment by DetachHead** [comment]
another example:

```yaml
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: macos-latest
            shell: bash
          - name: windows-latest
            shell: powershell
          - name: ubuntu-latest
            shell: bash

    runs-on: ${{ matrix.os.name }}
    steps:
      - run: 'uv sync'
        shell: ${{ matrix.os.shell }} # error: Unrecognized named-value: 'matrix'
```
