### ISSUE TITLE
Error thrown in consuming workflows regarding JSON output values quotes

### ISSUE THREAD

**Issue by avaly** [github/vscode-github-actions#464]
**Describe the bug**

Quotes in a reusable workflow's JSON output value is triggering an error in consuming workflows.

**To Reproduce**

1. Create a reusable workflow with input and outputs, one of the output being this JSON value:

```yaml
    outputs:
      images:
        value: '{"gcp": "${{ contains(inputs.registries, ''gcp'') && jobs.setup.outputs.gcp_image || '''' }}", "ecr": "${{ contains(inputs.registries, ''ecr'') && jobs.setup.outputs.ecr_image || ''''  }}"}'
```

2. Use the first workflow in another workflow:

```yaml
  build:
    uses: acme/actions/.github/workflows/build.yaml@v1
```

3. See the following errors in the 2nd workflow file, but __at the line number__ from the 1st workflow file:

```
Unexpected symbol: 'gcp'''. Located at position 31 within expression: contains(inputs.registries, ''gcp'') && jobs.setup.outputs.gcp_image || '''' [Ln 72, Col 26]
Unexpected symbol: 'ecr'''. Located at position 31 within expression: contains(inputs.registries, ''ecr'') && jobs.setup.outputs.ecr_image || '''' [Ln 72, Col 120]
```

**Expected behavior**

The 1st workflow does not throw any errors when being run in Github Actions runners, so I'd expect no errors to be printed by this extension.

**Extension Version**

`v0.27.1`
