### ISSUE TITLE
Support Custom GitHub Action use of GITHUB_ENV

### ISSUE THREAD

**Issue by rlespinasse** [github/vscode-github-actions#47]
**Is your feature request related to a problem? Please describe.**
Some GitHub Actions use `GITHUB_ENV` to set up custom environment variables.
When used inside a workflow, use `${{ env.CUSTOM_VARIABLE }}` is flagged as `Context access might be invalid`. 

**Describe the solution you'd like**
Enable the custom GitHub Actions developer to define statically or dynamically the generated environment variables (like for the action output) and use it in this plugin to remove false-positive.

**Additional context**

This workflow is flagged with the issue

```yaml
name: "Context access might be invalid"
on: push
jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      - name: Print custom environment variables
        run: echo ${{ env.GITHUB_REF_SLUG }}
```
And produces
<img width="535" alt="Capture d’écran 2023-03-28 à 20 15 36" src="https://user-images.githubusercontent.com/1280212/228331163-d7be2fa4-63c9-453a-a59d-6656e9b113d1.png">

**Comment by kristof-mattei** [comment]
Another example:

```
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Something

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if we actually made changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/file-filters.yml

      - shell: bash
        run: |
          echo ${{ fromJSON(env.SOME_ENV) }}

```

![image](https://user-images.githubusercontent.com/864376/228420646-28edc015-15e1-4a85-a819-0e73253049ee.png)

**Comment by rdhar** [comment]
Same here; additions to `GITHUB_ENV` return "Context access might be invalid: REF" warning. 
This is true for both expressions (i.e., `if: env.REF`) as well as environment variable interpolation (i.e., `${{ env.REF }}`).

Here's a [workflow snippet](https://github.com/o11y-top/aws-terraform-multiple-environments/blob/main/.github/workflows/terraform.yml#L129-L135) with the same warning on every `env.REF` line, despite these environment variables being initialised in the previous step. 

```yaml
steps:
  - name: Add environment variable
    run: echo REF=${string/--*/} >> $GITHUB_ENV

  - name: Reference environment variable
    if: env.REF != 'default' # Context access might be invalid: REF
    uses: actions/github-script@v6
    with:
      script: return "${{ env.REF }}" # Context access might be invalid: REF
```

Thank you.

**Comment by briantist** [comment]
I understand this warning in that there is probably no way for the extension to determine that the var will exist at runtime, so it will never be able to definitively know when to warn or not.

So I think what we need is a way to tell the extension not to warn on certain vars, perhaps even scoped.

Probably something comment based like other linters use., maybe a `noqa` type of thing.

```yaml
name: "Context access might be invalid"
on: push
jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      # noqa: runtime-reference GITHUB_REF_SLUG
      - name: Print custom environment variables
        run: echo ${{ env.GITHUB_REF_SLUG }}
```

Scoping would be neat, like somehow applying the `noqa` and then disabling it, so that you can mark the area where it should not apply instead of having it never validate that variable again in the whole workflow.

---

## Workaround

This can be worked around by explicitly adding the variable to an `env` block anywhere before the reference in the workflow:

```yaml
name: "Context access might be invalid"
on: push
env:
  GITHUB_REF_SLUG: ""

jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      - name: Print custom environment variables
        run: echo ${{ env.GITHUB_REF_SLUG }}
```

This is not a great workaround imo, because it masks the real issue, and means littering the workflow with useless references. Worse, it makes it more difficult to understand the workflow.

---

There are also some errors with the variable flagging (it misses some!) which I'll raise in another issue.
