### ISSUE TITLE
referencing `github` context in `workflow_call` is allowed but pointed out as error

### ISSUE THREAD

**Issue by sarisia** [github/vscode-github-actions#54]
**Describe the bug**

Referencing `github` context variable in `on.workflow_call.inputs.<name>.default` is allowed and works in
GitHub Actions but the extension points out them as an error: `Unexpected type 'BasicExpressionToken' encountered while reading 'input default'. The type 'StringToken' was expected.`

![image](https://user-images.githubusercontent.com/33576079/228480323-6469cdab-55bd-4dc0-be58-08768a45e611.png)

**To Reproduce**

1. create `.github/workflows/workflow.yml`:

```yaml
on:
  workflow_call:
    inputs:
      image-name:
        type: string
        description: Image name to push, including registry
        default: ghcr.io/${{ github.repository }}/devcontainer
```

**Expected behavior**
This won't be an error

**Extension Version**
`v0.25.3`
