### ISSUE TITLE
`if` conditional marked as error if the YAML string is double quoted

### ISSUE THREAD

**Issue by briantist** [github/vscode-github-actions#60]
**Describe the bug**
I have an `if` in my workflow that looks like this:
```yaml
if: "!startsWith(matrix.os, 'ubuntu-')"
```

The conditional is quoted because `!` has meaning in YAML to change the type, so we can't start a string with that character without a way to tell the YAML parser it's a string. **This works fine in the workflow.**

However, it's marked as an error by this extension:

> Unexpected symbol: '"'. Located at position 1 within expression: "!startsWith(matrix.os, 'ubuntu-')"

**Workarounds that work**
* Single quotes
* YAML multi-line strings
* Unnecessary templating

```yaml
---
if: '!startsWith(matrix.os, "ubuntu-")'

---
if: >-
  !startsWith(matrix.os, 'ubuntu-')

---
if: ${{ !startsWith(matrix.os, 'ubuntu-') }}
```

**Workarounds that don't work**
* explicit `str` typing

```yaml
---
if: !!str !startsWith(matrix.os, 'ubuntu-')
```

**To Reproduce**
Use a double quoted condition.

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/1260690/228541620-d2aac670-d445-4b49-ba4e-26e841c63cfb.png)

**Extension Version**
`v0.25.3`

**Comment by passcod** [comment]
Noting that the workarounds also cause the conditional to not syntax-highlight anymore (a more minor annoyance to be sure, though).

**Comment by passcod** [comment]
Another workaround which does preserve syntax highlighting is to wrap with `()` instead:

```diff
-    - if: "!startsWith(github.ref, 'refs/heads/release/')"
+    - if: (!startsWith(github.ref, 'refs/heads/release/'))
```

**Comment by ssbarnea** [comment]
Considering the lack of comments from any maintainers I am even wondering if we should assume this extension is abandonware, last release was like 9 months ago and an error like this is nowhere to be considered as a minor.

**Comment by muzimuzhi** [comment]
Not-reproducible in 0.28.2. Guess this has been fixed in recent https://github.com/actions/languageservices versions.

```yaml
name: temp
on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Runs on Ubuntu runner."
        if: "!startsWith(matrix.os, 'ubuntu-')"
```
