### ISSUE TITLE
Workflow expression variable reference checks miss some variables

### ISSUE THREAD

**Issue by briantist** [github/vscode-github-actions#61]
**Describe the bug**
The expression checker looks to see if variables that are referenced are actually defined and warns if a context reference may not be valid. This can cause bugs like #47 , but also it's missing some variables completely.

From the above issue:

```yaml
name: "Context access might be invalid"
on: push
jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      - name: Print custom environment variables
        run: echo ${{ env.GITHUB_REF_SLUG }}
```

This raises the `Context access might be invalid` warning for `env.GITHUB_REF_SLUG`.

If the expression itself branches like so, only the ~"false"~ path as evaluated in the extension will raise a warning:

```yaml
name: "Context access might be invalid"
on: push
jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      - name: Print custom environment variables
        run: echo ${{ true == false && env.FAKE_VAR || env.GITHUB_REF_SLUG }}
```

Here, the warning will be raised again, but only for `env.GITHUB_REF_SLUG`.

If we "define" the env var in an `env` block explicitly:

```yaml
name: "Context access might be invalid"
on: push
jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      - name: Print custom environment variables
        env:
          GITHUB_REF_SLUG: whatever
        run: echo ${{ true == false && env.FAKE_VAR || env.GITHUB_REF_SLUG }}
```

then the warning goes away completely, and `env.FAKE_VAR` is never considered.

Alternatively, if we change the expression to something that can be evaluated as `true` at parse time:

```yaml
name: "Context access might be invalid"
on: push
jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      - name: Print custom environment variables
        run: echo ${{ true && env.FAKE_VAR || env.GITHUB_REF_SLUG }}
```

Then the warning will change to `env.FAKE_VAR` only, ignoring the other one.

**To Reproduce**
See above.

**Expected behavior**
Both vars are warned against.

**Extension Version**
`v0.25.3`
