### ISSUE TITLE
"No repositories found" when on branch that is not default

### ISSUE THREAD

**Issue by AdamRaichu** [github/vscode-github-actions#78]
**Describe the bug**

When on a non-default branch of a repository, the extension view claims there are no GitHub repositories present.

**To Reproduce**
1. Open a branch of a repository that is not the default.
2. Open the view contributed by the extension.
3. Observe error message.

**Expected behavior**
The extension should recognize the repository, but should warn the user that this is not the default branch. Also, `workflow_dispatch` workflows should be able to be run on non-default branches as they are in the web interface.

**Screenshots**

![image](https://user-images.githubusercontent.com/91494019/229171089-345555f3-f7da-4a54-8865-639d4469f328.png)

**Extension Version**
`v0.25.3`

**Additional context**

Workflow file on that branch (same as on default branch).

```yaml
name: Publish Extension
on:
  workflow_dispatch:
    inputs:
      preRelease:
        type: boolean
        required: true
        default: false
      continueOnTagErr:
        type: boolean
        required: false
        default: false
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - uses: nyaa8/package-version@v1
      - name: Create a tag
        continue-on-error: ${{ inputs.continueOnTagErr }}
        run: |
          git config user.name = "Github Actions"
          git config user.email = "actions@github.com"
          git tag -a v${{ env.PACKAGE_VERSION }} -m "Version ${{ env.PACKAGE_VERSION }}"
          git push origin v${{ env.PACKAGE_VERSION }}
      - name: Generate Files
        run: |
          npm i
          npm run build
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.AZURE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          preRelease: ${{ inputs.preRelease }}
```

This pull associated with this branch is almost ready to merge so my specific example will no longer be available soon, but this should work with other repos.
